import { readFile, writeFile } from 'node:fs/promises';
import { transformFileAsync } from '@babel/core';
import stylexPlugin from '@stylexjs/babel-plugin';

const result = await transformFileAsync(new URL('./src/styles.js', import.meta.url).pathname, {
  babelrc: false,
  configFile: false,
  plugins: [[stylexPlugin, { dev: false, runtimeInjection: false }]],
});
// Evaluate only our compiled styles at build time; no JavaScript ships to visitors.
const { default: classes } = await import(
  `data:text/javascript;base64,${Buffer.from(result.code.replace(
    /from ['"]@stylexjs\/stylex['"]/g,
    `from '${import.meta.resolve('@stylexjs/stylex')}'`,
  )).toString('base64')}`
);
const css = stylexPlugin.processStylexRules(result.metadata.stylex);
const template = await readFile(new URL('./src/index.html', import.meta.url), 'utf8');
const html = template.replace(/\{\{(\w+)\}\}/g, (_, name) => {
  const value = name === 'css' ? css : classes[name];
  if (!value) throw new Error(`Unknown template token: ${name}`);
  return value;
});
await writeFile(new URL('./index.html', import.meta.url), '<!-- Generated by npm run build; edit src/ instead. -->\n' + html);
console.log(`Built index.html (${Buffer.byteLength(html)} bytes; zero client JavaScript)`);
